project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  reader-mode: false
  title: "Jo's Networking Notes"
  

  
  sidebar:
    border: true
    background: dark
    logo: ""
    pinned: true
    align: center
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/jonathan-roy-/
        text: "LinkedIn"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: Network Infrastructure
        contents: 
          - href: cef-rib.qmd 
            text: "CEF Table(FIB) and Routing Table"
          - section: Switched campus
            contents:
                - href: switch_administration.qmd 
                  text: "Switch administration (MAC, MTU, Errdisable)"
                - Layer 2 protocols (CDP, LLDP, UDLD)
                - VLAN technologies
                - EtherChannel
                - Spanning Tree Protocol
          - section: Routing Concepts
            contents:
               - href: administrative_distance.qmd
                 text: "Administrative distance"
               - href: vrf-lite.qmd
                 text: "VRF-lite"
               - Static routing
               - Policy Based Routing
               - Route filtering
               - Manual summarization
               - Redistribution
               - Routing protocol authentication
               - Bidirectional Forwarding Detection
          - section: EIGRP
            contents:
               - Concept
               - Legacy conf mode
               - Named conf mode
          - section: OSPF
            contents:
               - Concept
               - Version 2
               - Version 3
          - section: BGP
            contents:
               - Concept
               - Path selection
               - Configuration                             
          - section: Multicast
            contents:
               - Layer 2 multicast
               - Reverse path forwarding check
               - PIM                 
      - section: Transport Technologies and Solutions   
        contents: 
          - section: MPLS
            contents:
                - href: mpls_concept.qmd 
                  text: "MPLS Concept"
                - href: mpls_layer_3 _vpn.qmd 
                  text: "MPLS Layer 3 VPN"
          - section: DMVPN
            contents:
                - Concept
                - Phase 1-2-3                
      - section: Infrastructure Security and Services   
        contents: 
          - section: Device Security
            contents:
                - Control plane policing and protection
                - AAA
          - section: Network Security
            contents:
                - section: Switch security features
                  contents:                    
                    - VACL, PACL
                    - Storm control                
                    - DHCP Snooping, DHCP option 82
                    - IP Source Guard 
                    - Dynamic ARP Inspection
                    - Port Security                
                    - Private VLAN
                    
                - section: Router security features
                  contents:                    
                    - href: ipv4_acl.qmd
                      text: "IPv4 Access Control Lists"
                    - href: IPv6-traffic-filter.qmd
                      text: "IPv6 Traffic Filters"
                    - Unicast Reverse Path Forwarding
                    - href: unicast_reverse_path_forwarding.qmd
                      text: "Unicast reverse path forwardin uRPF"
                - href: IPv6_first_hop_security.qmd
                  text: "IPv6 First Hop security features"
                -  IEEE 802.1X Port-Based Authentication
                    
          - section: System Management
            contents:
                - section: Device management
                  contents:                    
                    - Console and VTY
                    - SSH, SCP         
                    - RESTCONF, NETCONF
                - SNMP
                - Logging
          - section: Quality of Service
            contents:                    
                - DiffServ    
                - CoS and DSCP Mapping
                - Classification
                - Network Based Application Recognition (NBAR)
                - Policing, shaping
                - Congestion management and avoidance
                
          - section: Network Services
            contents:                    
                - section: First Hop Redundancy Protocols
                  contents:                    
                    - HSRP
                    - GLBP, VRRP
                    - Redundancy using IPv6 RS/RA
                - Network Time Protocol
                
                - section: DHCP on Cisco IOS
                  contents:                    
                    - Client, server, relay
                    - Options
                    - SLAAC/DHCPv6 interaction  
                    - Stateful, stateless DHCPv6
                    - DHCPv6 Prefix Delegation

                - section: IPv4 Network Address Translation
                  contents:                    
                    - Static NAT, PAT
                    - Dynamic NAT, PAT
                    - Policy-based NAT, PAT 
                    - VRF-aware NAT, PAT
                    - DHCPv6 Prefix Delegation                

          - section: Network optimization
            contents:
              - IP SLA
              - Tracking object
              - Flexible NetFlow
            
          - section: Network operations
            contents:                    
                - section: Traffic capture
                  contents:                    
                    - SPAN
                    - RSPAN
                    - ERSPAN
                    - Embedded Packet Capture
   
format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 250px
      gutter-width: 1.5rem



