project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  reader-mode: false
  title: "Jo's Networking Notes"

  
  sidebar:
    background: dark
    logo: ""
    pinned: true
    align: center
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/jonathan-roy-/
        text: "LinkedIn"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: L3 Technologies
        contents: 
          - Test1.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



