project:
  type: website

website:
  title: "Jo's Networking Notes"
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



